version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/rocket
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pipenv
            export PIPENV_VENV_IN_PROJECT=~/rocket
            pipenv install
            ls -al
      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: Run Static Analysis
          command: |
            cd rocket
            pipenv run flake8
      - run:
          name: Run Tests
          command: |
            cd rocket
            pipenv run pytest
