# Generated by Django 2.1.1 on 2018-09-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('ip', models.CharField(max_length=100)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environments.Environment')),
            ],
        ),
    ]
